apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-analyzer
  namespace: monitoring
  labels:
    app: metrics-analyzer
spec:
  selector:
    matchLabels:
      app: metrics-analyzer
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
    path: /metrics
    interval: 15s

